name: Create to Azure VM

env:
  OUTPUT_PATH: ${{ github.workspace }}

on: [push]

jobs:

  # Deploy VM in Azure
  DeployVM:
    runs-on: windows-latest

    steps:
      # checkout code from repo
      - name: checkout repo
        uses: actions/checkout@v1

      - name: locate vm script
        run: |
          ls '${{ env.OUTPUT_PATH }}\scripts\'
      - name: Provision Azure VM
        env:
          RESOURCE_GROUP: rg-isitupbot
          RESOURCE_GROUP_REGION: useast
          SERVER_NAME: isitupbot
          ADMIN_LOGIN: zuri
        run: >
          powershell -command "& '${{ env.OUTPUT_PATH }}\scripts\vm.ps1'"
          -servicePrincipal ${{ secrets.SERVICE_PRINCIPAL_APPID }}
          -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
          -servicePrincipalTenantId ${{ secrets.SERVICE_PRINCIPAL_TENANTID }}
          -azureSubscriptionName ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          -resourceGroupName %RESOURCE_GROUP%
          -resourceGroupNameRegion %RESOURCE_GROUP_REGION%
          -serverName %SERVER_NAME%
          -adminLogin %ADMIN_LOGIN%
          -adminPassword ${{ secrets.ADMIN_PASSWORD }}